from datetime import timedelta

FAILED_PROMO_ATTEMPT_RESULTS = ("INVALID", "EXPIRED", "NOT_APPLICABLE")
PROMO_ATTEMPT_BLOCK_WINDOW = timedelta(hours=1)
PROMO_ATTEMPT_RATE_LIMIT_WINDOW = timedelta(hours=24)
PROMO_ATTEMPT_MAX_FAILURES = 5
PROMO_DISCOUNT_RESERVATION_TTL = timedelta(days=7)
PROMO_PREMIUM_SCOPE_BY_DAYS: dict[int, str] = {
    7: "PREMIUM_STARTER",
    30: "PREMIUM_MONTH",
    90: "PREMIUM_SEASON",
}
