PREMIUM_SCOPE_STARTER = "PREMIUM_STARTER"
PREMIUM_SCOPE_MONTH = "PREMIUM_MONTH"
PREMIUM_SCOPE_SEASON = "PREMIUM_SEASON"
PREMIUM_SCOPE_YEAR = "PREMIUM_YEAR"

MONTHLY_PREMIUM_FREEZE_LIMIT = 1
BERLIN_TIMEZONE = "Europe/Berlin"
