from __future__ import annotations

PROMO_FAILURE_RESULTS = ("INVALID", "EXPIRED", "NOT_APPLICABLE", "RATE_LIMITED")
PROMO_GUARD_LOOKBACK_MINUTES = 10
PROMO_GUARD_MIN_FAILED_ATTEMPTS = 100
PROMO_GUARD_MIN_DISTINCT_USERS = 2
PROMO_CAMPAIGN_STATUSES = {"ACTIVE", "PAUSED", "EXPIRED", "DEPLETED"}
PROMO_MUTABLE_CAMPAIGN_STATUSES = {"ACTIVE", "PAUSED"}
PROMO_ALLOWED_STATUS_TRANSITIONS = {("ACTIVE", "PAUSED"), ("PAUSED", "ACTIVE")}
REFUNDABLE_PURCHASE_STATUSES = {"CREDITED", "PAID_UNCREDITED"}
