from __future__ import annotations

TOURNAMENT_TYPE_PRIVATE = "PRIVATE"

TOURNAMENT_STATUS_REGISTRATION = "REGISTRATION"
TOURNAMENT_STATUS_ROUND_1 = "ROUND_1"
TOURNAMENT_STATUS_ROUND_2 = "ROUND_2"
TOURNAMENT_STATUS_ROUND_3 = "ROUND_3"
TOURNAMENT_STATUS_COMPLETED = "COMPLETED"
TOURNAMENT_STATUS_CANCELED = "CANCELED"

TOURNAMENT_MATCH_STATUS_PENDING = "PENDING"
TOURNAMENT_MATCH_STATUS_COMPLETED = "COMPLETED"
TOURNAMENT_MATCH_STATUS_WALKOVER = "WALKOVER"

TOURNAMENT_FORMAT_QUICK_5 = "QUICK_5"
TOURNAMENT_FORMAT_QUICK_12 = "QUICK_12"

TOURNAMENT_MODE_CODE = "QUICK_MIX_A1A2"
TOURNAMENT_MAX_ROUNDS = 3
TOURNAMENT_DEFAULT_MAX_PARTICIPANTS = 8
TOURNAMENT_DEFAULT_REGISTRATION_HOURS = 24
TOURNAMENT_DEFAULT_ROUND_DURATION_HOURS = 24


def rounds_for_tournament_format(*, format_code: str) -> int:
    if format_code == TOURNAMENT_FORMAT_QUICK_5:
        return 5
    if format_code == TOURNAMENT_FORMAT_QUICK_12:
        return 12
    raise ValueError(format_code)


def status_for_round(*, round_no: int) -> str:
    if round_no == 1:
        return TOURNAMENT_STATUS_ROUND_1
    if round_no == 2:
        return TOURNAMENT_STATUS_ROUND_2
    if round_no == 3:
        return TOURNAMENT_STATUS_ROUND_3
    raise ValueError(round_no)
