from __future__ import annotations

DUEL_MODE_ARENA = "OFFENE_ARENA"
DUEL_MODE_FRIEND = "FREUNDESDUELL"

DUEL_QUESTION_COUNT = 7
DUEL_CAN_SELECT_TOPIC = False
DUEL_CAN_SELECT_LEVEL = False
DUEL_CAN_SELECT_QUESTION_COUNT = False

DUEL_PAYWALL_PRODUCT_CODES: tuple[str, str] = ("FRIEND_CHALLENGE_5", "PREMIUM_WEEK")
DUEL_PREMIUM_REWARD_ONLY_PRODUCT_CODE = "PREMIUM_3_DAYS"

DUEL_MENU_CALLBACK = "duels:menu"
DUEL_ARENA_CALLBACK = "duels:arena"
DUEL_FRIEND_CALLBACK = "duels:friend"

ARENA_LIST_CALLBACK = "arena:list"
ARENA_CREATE_CALLBACK = "arena:create"
ARENA_START_CREATE_CALLBACK = "arena:start_create"
ARENA_ACCEPT_CALLBACK_PREFIX = "arena:accept:"
ARENA_START_ATTEMPT_CALLBACK_PREFIX = "arena:start_attempt:"
ARENA_PUBLISH_FRIEND_CALLBACK_PREFIX = "arena:publish_friend:"

FRIEND_DUEL_CREATE_CALLBACK = "friend:challenge:format:direct:7"

DUEL_CANONICAL_CALLBACKS: tuple[str, ...] = (
    DUEL_MENU_CALLBACK,
    DUEL_ARENA_CALLBACK,
    DUEL_FRIEND_CALLBACK,
    ARENA_LIST_CALLBACK,
    ARENA_CREATE_CALLBACK,
    ARENA_START_CREATE_CALLBACK,
)
