from __future__ import annotations

DUEL_MODE_ARENA = "OFFENE_ARENA"
DUEL_MODE_FRIEND = "FREUNDESDUELL"

DUEL_QUESTION_COUNT = 7
DUEL_CAN_SELECT_TOPIC = False
DUEL_CAN_SELECT_LEVEL = False
DUEL_CAN_SELECT_QUESTION_COUNT = False

DUEL_PAYWALL_PRODUCT_CODES: tuple[str, str] = ("FRIEND_CHALLENGE_5", "PREMIUM_WEEK")
DUEL_PREMIUM_REWARD_ONLY_PRODUCT_CODE = "PREMIUM_3_DAYS"
DUEL_TICKET_PRODUCT_CODE = DUEL_PAYWALL_PRODUCT_CODES[0]
DUEL_PREMIUM_WEEK_PRODUCT_CODE = DUEL_PAYWALL_PRODUCT_CODES[1]

DUEL_LIMIT_ACTION_ARENA_ACCEPT = "ARENA_ACCEPT"
DUEL_LIMIT_ACTION_ARENA_CREATE = "ARENA_CREATE"
DUEL_LIMIT_ACTION_FRIEND_CREATE = "FRIEND_CREATE"
DUEL_LIMIT_ACTION_REVANCHE = "REVANCHE"
DUEL_FREE_LIMITS_PER_DAY: dict[str, int] = {
    DUEL_LIMIT_ACTION_ARENA_ACCEPT: 3,
    DUEL_LIMIT_ACTION_ARENA_CREATE: 1,
    DUEL_LIMIT_ACTION_FRIEND_CREATE: 2,
    DUEL_LIMIT_ACTION_REVANCHE: 1,
}
DUEL_LIMITED_SESSION_SOURCES = frozenset({"ARENA_DUEL"})

DUEL_MENU_CALLBACK = "duels:menu"
DUEL_ARENA_CALLBACK = "duels:arena"
DUEL_FRIEND_CALLBACK = "duels:friend"

ARENA_LIST_CALLBACK = "arena:list"
ARENA_CREATE_CALLBACK = "arena:create"
ARENA_START_CREATE_CALLBACK = "arena:start_create"
ARENA_ACCEPT_CALLBACK_PREFIX = "arena:accept:"
ARENA_START_ATTEMPT_CALLBACK_PREFIX = "arena:start_attempt:"
ARENA_PUBLISH_FRIEND_CALLBACK_PREFIX = "arena:publish_friend:"

FRIEND_DUEL_CREATE_CALLBACK = "friend:challenge:format:direct:7"

DUEL_CANONICAL_CALLBACKS: tuple[str, ...] = (
    DUEL_MENU_CALLBACK,
    DUEL_ARENA_CALLBACK,
    DUEL_FRIEND_CALLBACK,
    ARENA_LIST_CALLBACK,
    ARENA_CREATE_CALLBACK,
    ARENA_START_CREATE_CALLBACK,
)
