from __future__ import annotations

from datetime import datetime, timedelta

ARENA_SOURCE = "ARENA_DUEL"

ARENA_DUEL_STATUS_DRAFT = "DRAFT"
ARENA_DUEL_STATUS_ACTIVE = "ACTIVE"
ARENA_DUEL_STATUS_EXPIRED = "EXPIRED"
ARENA_DUEL_STATUS_CANCELLED = "CANCELLED"

ARENA_ATTEMPT_ROLE_CREATOR_BASELINE = "CREATOR_BASELINE"
ARENA_ATTEMPT_ROLE_CHALLENGER = "CHALLENGER"

ARENA_ATTEMPT_RESULT_BASELINE = "BASELINE"
ARENA_ATTEMPT_RESULT_WIN = "WIN"
ARENA_ATTEMPT_RESULT_LOSS = "LOSS"
ARENA_ATTEMPT_RESULT_DRAW = "DRAW"

ARENA_RESULT_REASON_SCORE = "SCORE"
ARENA_RESULT_REASON_TIME = "TIME"
ARENA_RESULT_REASON_EXACT_TIE = "EXACT_TIE"

ARENA_DUEL_TTL = timedelta(hours=24)
ARENA_DEFAULT_ACTIVE_LIST_LIMIT = 10


def arena_duel_expires_at(*, now_utc: datetime) -> datetime:
    return now_utc + ARENA_DUEL_TTL
