from __future__ import annotations

_QUICK_MIX_ITEMS_A: tuple[tuple[str, str, tuple[str, str, str, str], int, str, str], ...] = (
    (
        "qm_a1a2_001",
        "Ich ___ aus Berlin.",
        ("bin", "bist", "seid", "sind"),
        0,
        "A1",
        "Verb_Conjugation",
    ),
    (
        "qm_a1a2_002",
        "Du ___ heute viel Wasser trinken.",
        ("musst", "muss", "müssen", "musstet"),
        0,
        "A1",
        "Modalverben",
    ),
    ("qm_a1a2_003", "Ich habe ___ Zeit.", ("keine", "kein", "nicht", "nie"), 0, "A1", "Negation"),
    (
        "qm_a1a2_004",
        "Was ist der Plural von 'Tag'?",
        ("Tage", "Tags", "Tagen", "Tagee"),
        0,
        "A1",
        "Plural_Check",
    ),
    ("qm_a1a2_005", "___ heißt du?", ("Wie", "Wo", "Wann", "Warum"), 0, "A1", "W_Fragen"),
    (
        "qm_a1a2_006",
        "Ich wohne ___ Berlin.",
        ("in", "an", "auf", "bei"),
        0,
        "A1",
        "Preposition_Selection",
    ),
    (
        "qm_a1a2_007",
        "Das ist ___ Bruder.",
        ("mein", "meine", "meinen", "meinem"),
        0,
        "A1",
        "Possessive_Adjectives",
    ),
    (
        "qm_a1a2_008",
        "Im Klassenzimmer schreibt man mit einem ___.",
        ("Stift", "Teller", "Bett", "Schuh"),
        0,
        "A1",
        "Topic_Vocabulary_Themes",
    ),
    (
        "qm_a1a2_009",
        "Ich kaufe einen ___ Mantel.",
        ("warmen", "warme", "warmes", "warm"),
        0,
        "A2",
        "Adjektivendungen",
    ),
    (
        "qm_a1a2_010",
        "Wir ___ morgen ins Kino.",
        ("gehen", "geht", "gehe", "ging"),
        0,
        "A2",
        "Verb_Conjugation",
    ),
    (
        "qm_a1a2_011",
        "A: Hast du Hunger? B: Ja, ich möchte ___ essen.",
        ("etwas", "nie", "kein", "weg"),
        0,
        "A2",
        "Mini_Dialog",
    ),
    (
        "qm_a1a2_012",
        "Er kommt heute ___.",
        ("nicht", "kein", "keine", "nichts"),
        0,
        "A2",
        "Negation",
    ),
    (
        "qm_a1a2_013",
        "Was ist der Plural von 'Museum'?",
        ("Museen", "Museums", "Musee", "Musen"),
        0,
        "A2",
        "Plural_Check",
    ),
    (
        "qm_a1a2_014",
        "___ fängt der Kurs an? Um neun Uhr.",
        ("Wann", "Wie", "Wer", "Wohin"),
        0,
        "A2",
        "W_Fragen",
    ),
    (
        "qm_a1a2_015",
        "Das Bild hängt ___ der Wand.",
        ("an", "in", "auf", "unter"),
        0,
        "A2",
        "Preposition_Selection",
    ),
)
