from __future__ import annotations

_QUICK_MIX_ITEMS_B: tuple[tuple[str, str, tuple[str, str, str, str], int, str, str], ...] = (
    (
        "qm_a1a2_016",
        "Sie besucht ___ Großeltern am Sonntag.",
        ("ihre", "ihr", "ihren", "ihres"),
        0,
        "A2",
        "Possessive_Adjectives",
    ),
    (
        "qm_a1a2_017",
        "Was ist das Gegenteil von 'laut'?",
        ("leise", "langsam", "leer", "tief"),
        0,
        "B1",
        "Antonym",
    ),
    (
        "qm_a1a2_018",
        "Welches Wort passt am besten zu 'beginnen'?",
        ("anfangen", "beenden", "sammeln", "verlieren"),
        0,
        "B1",
        "Synonym_Match",
    ),
    (
        "qm_a1a2_019",
        "Wenn ich mehr Zeit hätte, ___ ich öfter kochen.",
        ("würde", "werde", "wurde", "werde ich"),
        0,
        "B1",
        "Lexical_Gap_Fill",
    ),
    (
        "qm_a1a2_020",
        "Man ___ hier nicht rauchen.",
        ("darf", "dürfen", "durfte", "darfst"),
        0,
        "B1",
        "Modalverben",
    ),
    (
        "qm_a1a2_021",
        "Sie trägt ein ___ Kleid.",
        ("elegantes", "elegante", "elegantem", "eleganter"),
        0,
        "B1",
        "Adjektivendungen",
    ),
    (
        "qm_a1a2_022",
        "Für eine Reise braucht man oft einen ___.",
        ("Reisepass", "Fernseher", "Teppich", "Löffel"),
        0,
        "B1",
        "Topic_Vocabulary_Themes",
    ),
    (
        "qm_a1a2_023",
        "A: Warum bist du zu spät? B: ___ der Zug Verspätung hatte.",
        ("Weil", "Obwohl", "Damit", "Wenn"),
        0,
        "B1",
        "Mini_Dialog",
    ),
    (
        "qm_a1a2_024",
        "Er nahm den Schirm mit, ___ der Himmel noch blau war.",
        ("obwohl", "weil", "damit", "denn"),
        0,
        "B2",
        "LOGIK_LUECKE",
    ),
    (
        "qm_a1a2_025",
        "Welches Wort ist ein Synonym für 'schwierig'?",
        ("kompliziert", "locker", "ruhig", "günstig"),
        0,
        "B2",
        "Synonym_Match",
    ),
    (
        "qm_a1a2_026",
        "Was ist das Gegenteil von 'Erfolg'?",
        ("Misserfolg", "Fortschritt", "Gewinn", "Vorteil"),
        0,
        "B2",
        "Antonym",
    ),
    (
        "qm_a1a2_027",
        "Sie interessiert sich sehr ___ nachhaltige Architektur.",
        ("für", "an", "auf", "über"),
        0,
        "B2",
        "Preposition_Selection",
    ),
    (
        "qm_a1a2_028",
        "Nachdem er das Buch ___, schrieb er eine Rezension.",
        ("gelesen hatte", "liest", "gelesen hat", "lesen würde"),
        0,
        "B2",
        "Verb_Conjugation",
    ),
    (
        "qm_a1a2_029",
        "Keines der Angebote war passend, also entschied er sich ___.",
        ("dagegen", "darauf", "darin", "damit"),
        0,
        "B2",
        "Negation",
    ),
    (
        "qm_a1a2_030",
        "Wir suchen eine ___ Lösung für das Problem.",
        ("langfristige", "langfristigen", "langfristiges", "langfristigem"),
        0,
        "B2",
        "Adjektivendungen",
    ),
)
