from __future__ import annotations

from .friend_challenges_repo_core import FriendChallengesRepoCoreMixin
from .friend_challenges_repo_deadlines import FriendChallengesRepoDeadlineMixin


class FriendChallengesRepo(FriendChallengesRepoCoreMixin, FriendChallengesRepoDeadlineMixin):
    pass
