from __future__ import annotations

from .processed_updates_repo_metrics import ProcessedUpdatesRepoMetricsMixin
from .processed_updates_repo_slots import ProcessedUpdatesRepoSlotsMixin


class ProcessedUpdatesRepo(ProcessedUpdatesRepoSlotsMixin, ProcessedUpdatesRepoMetricsMixin):
    pass
