from __future__ import annotations

from app.game.tournaments.constants import (
    TOURNAMENT_DEFAULT_ROUND_DURATION_HOURS,
    TOURNAMENT_MAX_ROUNDS,
)

DEADLINE_BATCH_SIZE = 50
SCAN_INTERVAL_SECONDS = 300
ROUND_DURATION_HOURS = TOURNAMENT_DEFAULT_ROUND_DURATION_HOURS
MAX_ROUNDS = TOURNAMENT_MAX_ROUNDS

__all__ = [
    "DEADLINE_BATCH_SIZE",
    "MAX_ROUNDS",
    "ROUND_DURATION_HOURS",
    "SCAN_INTERVAL_SECONDS",
]
