TEXTS_DE: dict[str, str] = {
    "msg.home.title": "Willkommen bei Quiz Arena.",
    "msg.home.energy": "Energie: {free_energy}/20 + {paid_energy} Bonus.",
    "msg.home.streak": "Serie: {streak} Tage.",
    "msg.system.error": "Es ist ein Fehler aufgetreten. Bitte versuche es erneut.",
    "msg.energy.empty.title": "Deine Energie ist leer.",
    "msg.energy.empty.body": "Du brauchst 1⚡ pro Quiz. Warte oder hol dir ein Paket.",
    "msg.locked.mode": "Dieser Modus ist gesperrt.",
    "msg.daily.challenge.free": "Daily Challenge ist heute kostenlos.",
    "msg.daily.challenge.used": "Du hast die Daily Challenge heute schon gespielt.",
    "msg.game.mode": "Modus: {mode_code}",
    "msg.game.answer.correct": "Richtig!",
    "msg.game.answer.incorrect": "Nicht ganz. Versuch es weiter!",
    "msg.game.streak": "Serie: {current_streak} | Beste: {best_streak}",
    "msg.game.session.not_found": "Diese Session ist nicht mehr verfügbar.",
    "msg.purchase.success.energy10": "Erfolg! +10 Energie wurde gutgeschrieben.",
    "msg.purchase.success.megapack": "Mega Pack aktiv. +15 Energie und 3 Modi sind jetzt freigeschaltet.",
    "msg.purchase.success.streaksaver": "Streak Saver ist bereit. Ein Fehltag wird automatisch geschützt.",
    "msg.purchase.success.premium": "Premium ist jetzt aktiv. Dein Zugriff wurde aktualisiert.",
    "msg.purchase.error.failed": "Zahlung fehlgeschlagen. Bitte versuche es erneut.",
    "msg.purchase.error.streaksaver.limit": "Streak Saver ist nur einmal in 7 Tagen verfügbar.",
    "msg.premium.downgrade.blocked": "Ein niedrigerer Plan ist während aktivem Premium nicht verfügbar.",
    "msg.offer.energy.low": "Nur noch wenig Energie. +10⚡ fuer 10⭐?",
    "msg.offer.energy.zero": "Du bist leer. Spiele jetzt weiter mit +10⚡ oder Mega Pack.",
    "msg.offer.mega.after_second_energy": "Du kaufst oft +10⚡. Mega Pack gibt dir mehr fuer weniger.",
    "msg.offer.locked.mode": "Dieser Modus ist gesperrt. Mega Pack schaltet ihn 24 Stunden frei.",
    "msg.offer.streak.risk": "Deine Serie ist in Gefahr. Spiele jetzt oder sichere sie mit Streak Saver.",
    "msg.offer.comeback": "Willkommen zurueck. Heute: +20 Energie geschenkt und Mega Pack Rabatt.",
    "msg.offer.starter.to.month": "Dein Starter ist vorbei. Mit Month bleibst du ohne Limits.",
    "msg.offer.month.to.season_year": "Du spielst konstant. Season und Year sparen dir Sterne.",
    "msg.offer.streak.gt7": "Starke Serie. Mit Mega Pack spielst du laenger ohne Pausen.",
    "msg.offer.streak.milestone.30": "30 Tage Serie! Schuetze sie mit Streak Saver oder geh auf Premium Month.",
    "msg.offer.mega.third.buy": "Du nutzt oft Mega Pack. Premium Starter macht es einfacher.",
    "msg.offer.weekend.flash": "Weekend Flash: Mega Pack ist diese Session besonders sinnvoll.",
    "msg.offer.dismissed": "Verstanden. Dieses Angebot bleibt 72 Stunden stumm.",
    "msg.referral.invite": "Lade Freunde ein und verdiene Belohnungen.",
    "msg.referral.progress": "Dein Fortschritt: {qualified}/3 qualifizierte Freunde.",
    "msg.referral.reward.choice": "Du hast eine Belohnung erreicht. Waehle deinen Bonus.",
    "msg.referral.rejected": "Diese Einladung zaehlt nicht fuer Belohnungen.",
    "msg.promo.input.hint": "Gib deinen Promo-Code ein. Beispiel: /promo WILLKOMMEN-50",
    "msg.promo.success.grant": "Promo-Code aktiviert. Premium wurde freigeschaltet.",
    "msg.promo.success.discount": "Promo-Code akzeptiert. Dein Rabatt ist 15 Minuten reserviert.",
    "msg.promo.error.invalid": "Dieser Promo-Code ist ungültig.",
    "msg.promo.error.expired": "Dieser Promo-Code ist abgelaufen.",
    "msg.promo.error.used": "Du hast diesen Promo-Code bereits verwendet.",
    "msg.promo.error.not_applicable": "Dieser Promo-Code passt nicht zu diesem Produkt.",
    "msg.promo.error.rate_limited": "Zu viele Versuche. Bitte versuche es später erneut.",
}
