TEXTS_DE: dict[str, str] = {
    "msg.home.title": "🎮 QUIZ ARENA",
    "msg.home.hint": "👇 Waehle unten eine Aktion.",
    "msg.home.energy": "Energie: {free_energy}/20 + {paid_energy} Bonus.",
    "msg.home.streak": "Serie: {streak} Tage.",
    "msg.shop.title": "Shop: Wähle ein Paket.",
    "msg.system.error": "Es ist ein Fehler aufgetreten. Bitte versuche es erneut.",
    "msg.energy.empty.title": "Deine Energie ist leer.",
    "msg.energy.empty.body": "Du brauchst 1⚡ pro Quiz. Warte oder hol dir ein Paket.",
    "msg.locked.mode": "Dieser Modus ist gesperrt.",
    "msg.daily.challenge.free": "Daily Challenge ist heute kostenlos.",
    "msg.daily.challenge.used": "🕒 Daily Challenge ist heute schon gespielt. Wieder ab 00:00 (Berlin).",
    "msg.game.mode": "⚡ {mode_code}",
    "msg.game.answer.correct": "✅ Richtig!",
    "msg.game.answer.incorrect": "❌ Nicht korrekt.",
    "msg.game.answer.selected": "Deine Antwort: {answer}",
    "msg.game.answer.correct_label": "Richtige Antwort: {answer}",
    "msg.game.energy.left": "🔋 Energie: {free_energy}/20 (+{paid_energy} Bonus)",
    "msg.game.theme": "📚 Thema: {theme}",
    "msg.game.question.counter": "❓ Frage {current}/{total}",
    "msg.game.choose_option": "👇 Waehle die richtige Antwort:",
    "msg.game.streak": "Serie: {current_streak} | Beste: {best_streak}",
    "msg.game.stopped": "Runde pausiert. Zurück im Hauptmenü.",
    "msg.game.daily.finished": "Daily Challenge beendet. Komm morgen wieder.",
    "msg.game.session.not_found": "Diese Session ist nicht mehr verfügbar.",
    "msg.friend.challenge.created": "🤝 Duell erstellt. Teile den Link mit deinem Freund.",
    "msg.friend.challenge.created.fallback": "🤝 Duell erstellt. Teile den Start-Code: fc_{invite_token}",
    "msg.friend.challenge.create.choose": "Waehle dein Duell: Sprint 3, Sprint 5 oder klassisch 12 Fragen.",
    "msg.friend.challenge.joined": "🤝 Du bist dem Duell beigetreten.",
    "msg.friend.challenge.with": "Duell mit: {opponent_label}",
    "msg.friend.challenge.opponent.joined": "✅ {opponent_label} ist deinem Duell beigetreten.",
    "msg.friend.challenge.plan": "12 Fragen Mix: A1 x3, A2 x6, B1 x3. Keine Energie-Kosten.",
    "msg.friend.challenge.invalid": "Dieses Duell ist nicht verfügbar.",
    "msg.friend.challenge.expired": "⌛ Dieses Duell ist wegen Zeitablauf beendet.",
    "msg.friend.challenge.full": "Dieses Duell hat schon zwei Spieler.",
    "msg.friend.challenge.limit.reached": "Deine 2 freien Duelle sind verbraucht. Kaufe 1 Duell fuer 5⭐ oder nimm Premium fuer unbegrenzte Duelle.",
    "msg.friend.challenge.created.short": "Teile den Link, dann tippe auf 'Duell starten'.",
    "msg.friend.challenge.waiting": "Warte auf deinen Freund. Sobald beide geantwortet haben, geht es weiter.",
    "msg.friend.challenge.play.instant": "Du kannst sofort alle {total_rounds} Fragen spielen. Runde-Ergebnisse kommen, sobald dein Freund antwortet.",
    "msg.friend.challenge.round.ready": "Beide Antworten sind da. Nächste Runde ist bereit.",
    "msg.friend.challenge.round.result": "Runde {round_no} ist abgeschlossen. Ergebnis aktualisiert.",
    "msg.friend.challenge.round.already.answered": "Du hast diese Runde schon beantwortet.",
    "msg.friend.challenge.all_answered.waiting": "Du hast alle {total_rounds} Fragen beantwortet. Warte auf {opponent_label}.",
    "msg.friend.challenge.score": "Duell Score: Du {my_score} | {opponent_label} {opponent_score}. Runde {round_now}/{total_rounds}.",
    "msg.friend.challenge.ttl": "⏳ Laeuft noch: {hours:02d}:{minutes:02d}h.",
    "msg.friend.challenge.finished.win": "🏆 Duell beendet. Sieger: Du.",
    "msg.friend.challenge.finished.lose": "Duell beendet. Sieger: {opponent_label}.",
    "msg.friend.challenge.finished.draw": "Duell beendet. Unentschieden.",
    "msg.friend.challenge.finished.expired": "⌛ Duell beendet. Zeit abgelaufen.",
    "msg.friend.challenge.finished.summary": "Finaler Score: Du {my_score} | {opponent_label} {opponent_score}.",
    "msg.friend.challenge.proof.title": "🧾 PROOF CARD",
    "msg.friend.challenge.proof.winner": "Sieger: {winner_label}",
    "msg.friend.challenge.proof.score": "Score: Du {my_score} | {opponent_label} {opponent_score}",
    "msg.friend.challenge.proof.format": "Format: Same Questions Duel ({total_rounds} Fragen)",
    "msg.friend.challenge.proof.signature": "Titel: {signature}",
    "msg.friend.challenge.proof.not_ready": "Proof Card ist erst nach Duell-Ende verfuegbar.",
    "msg.friend.challenge.proof.share.ready": "📤 Proof Card bereit. Tippe auf 'JETZT TEILEN'.",
    "msg.friend.challenge.proof.share.cta": "🔥 Same Questions Duel in Quiz Arena. Wer ist der Nächste?",
    "msg.friend.challenge.series.started": "🎯 Best of 3 gestartet gegen {opponent_label}.",
    "msg.friend.challenge.series.progress": "Serie: Spiel {game_no}/{best_of}. Score: Du {my_wins} | {opponent_label} {opponent_wins}.",
    "msg.friend.challenge.series.finished": "🏁 Serie beendet. Champion: {champion_label}.",
    "msg.friend.challenge.badge.public": "🏅 Public Badge: {badge_label}",
    "msg.friend.challenge.rematch.created": "🔁 Revanche erstellt gegen {opponent_label}.",
    "msg.friend.challenge.rematch.invite": "🔁 {opponent_label} fordert dich zur Revanche heraus.",
    "msg.purchase.success.energy10": "Erfolg! +10 Energie wurde gutgeschrieben.",
    "msg.purchase.success.friend_challenge_ticket": "Erfolg! 1 Duell-Ticket wurde aktiviert.",
    "msg.purchase.success.megapack": "Mega Pack aktiv. +15 Energie und 3 Modi sind jetzt freigeschaltet.",
    "msg.purchase.success.streaksaver": "Streak Saver ist bereit. Ein Fehltag wird automatisch geschützt.",
    "msg.purchase.success.premium": "Premium ist jetzt aktiv. Dein Zugriff wurde aktualisiert.",
    "msg.purchase.error.failed": "Zahlung fehlgeschlagen. Bitte versuche es erneut.",
    "msg.purchase.error.streaksaver.limit": "Streak Saver ist nur einmal in 7 Tagen verfügbar.",
    "msg.premium.downgrade.blocked": "Ein niedrigerer Plan ist während aktivem Premium nicht verfügbar.",
    "msg.offer.energy.low": "Nur noch wenig Energie. +10⚡ fuer 5⭐?",
    "msg.offer.energy.zero": "Du bist leer. Spiele jetzt weiter mit +10⚡ oder Mega Pack.",
    "msg.offer.mega.after_second_energy": "Du kaufst oft +10⚡. Mega Pack gibt dir mehr fuer weniger.",
    "msg.offer.locked.mode": "Dieser Modus ist gesperrt. Mega Pack schaltet ihn 24 Stunden frei.",
    "msg.offer.streak.risk": "Deine Serie ist in Gefahr. Spiele jetzt oder sichere sie mit Streak Saver.",
    "msg.offer.comeback": "Willkommen zurueck. Heute: +20 Energie geschenkt und Mega Pack Rabatt.",
    "msg.offer.starter.to.month": "Dein Starter ist vorbei. Mit Month bleibst du ohne Limits.",
    "msg.offer.month.to.season_year": "Du spielst konstant. Season und Year sparen dir Sterne.",
    "msg.offer.streak.gt7": "Starke Serie. Mit Mega Pack spielst du laenger ohne Pausen.",
    "msg.offer.streak.milestone.30": "30 Tage Serie! Schuetze sie mit Streak Saver oder geh auf Premium Month.",
    "msg.offer.mega.third.buy": "Du nutzt oft Mega Pack. Premium Starter macht es einfacher.",
    "msg.offer.weekend.flash": "Weekend Flash: Mega Pack ist diese Session besonders sinnvoll.",
    "msg.offer.dismissed": "Verstanden. Dieses Angebot bleibt 72 Stunden stumm.",
    "msg.referral.invite": "Lade Freunde ein und verdiene Belohnungen.",
    "msg.referral.progress": "Dein Fortschritt: {qualified}/3 qualifizierte Freunde.",
    "msg.referral.reward.choice": "Du hast eine Belohnung erreicht. Waehle deinen Bonus.",
    "msg.referral.link": "Teile deinen Einladungslink ueber die Taste 'Link teilen'.",
    "msg.referral.link.fallback": "Teile diesen Start-Code: ref_{referral_code}",
    "msg.referral.pending": "Offene Belohnungen: {pending}. Jetzt waehlbar: {claimable}.",
    "msg.referral.next_reward_at": "Naechste Belohnung verfuegbar ab: {next_reward_at} (Berlin).",
    "msg.referral.reward.claimed.megapack": "Belohnung aktiviert: Mega Pack.",
    "msg.referral.reward.claimed.premium": "Belohnung aktiviert: Premium Starter.",
    "msg.referral.reward.unavailable": "Aktuell ist keine Belohnung verfuegbar.",
    "msg.referral.reward.too_early": "Noch nicht freigeschaltet. Bitte warte auf den Delay.",
    "msg.referral.reward.monthly_cap": "Monatslimit erreicht. Neue Belohnungen folgen naechsten Monat.",
    "msg.referral.rejected": "Diese Einladung zaehlt nicht fuer Belohnungen.",
    "msg.promo.reply_prefix": "🎟 Promo-Code",
    "msg.promo.input.hint": "🎟 Promo-Code\nSende deinen Code jetzt als Antwort oder als normale Nachricht.\nBeispiel: WILLKOMMEN-50",
    "msg.promo.success.grant": "✅ Promo-Code aktiviert.",
    "msg.promo.success.grant.details": "Aktiviert: {premium_days} Tage Premium bis {premium_ends_at} (Berlin).",
    "msg.promo.success.discount": "✅ Promo-Code aktiviert.",
    "msg.promo.success.discount.details": "Aktiviert: {discount_percent}% Rabatt fuer {scope_label} bis {reserved_until} (Berlin).",
    "msg.promo.error.invalid": "❌ Promo-Code ungültig oder nicht aktiv. Prüfe den Code und versuche es erneut.",
    "msg.promo.error.expired": "❌ Dieser Promo-Code ist abgelaufen.",
    "msg.promo.error.used": "ℹ️ Diesen Promo-Code hast du bereits verwendet.",
    "msg.promo.error.not_applicable": "❌ Dieser Promo-Code gilt nicht für dieses Produkt.",
    "msg.promo.error.rate_limited": "⏳ Zu viele Versuche. Bitte versuche es später erneut.",
}
